name: "Setup Forklift"
description: Sets up the Forklift CLI in your GitHub Actions workflow.
inputs:
  version:
    description: Version of the Forklift CLI to install. Semver Ranges (https://www.npmjs.com/package/semver#ranges) are supported.
    required: false
    default: latest
  github-token:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to get the list of Forklift CLI versions. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
runs:
  using: node16
  main: dist/index.js
